# Generated by Django 3.0.5 on 2020-04-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20200408_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='House',
        ),
    ]
