# Generated by Django 3.0.5 on 2020-04-14 23:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20200414_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='dstv',
        ),
        migrations.RemoveField(
            model_name='house',
            name='wifi',
        ),
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'dstv': False, 'wifi': False}),
        ),
    ]
