# Generated by Django 3.0.5 on 2020-04-14 23:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import houses.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20200415_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=houses.models.my_default),
        ),
    ]
