# Generated by Django 3.0.5 on 2020-04-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_category_dstv_price_rooms_wifi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
