# Generated by Django 3.0.5 on 2020-04-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20200413_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dstv',
            name='dstv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='wifi_support',
            field=models.BooleanField(default=False),
        ),
    ]
