# Generated by Django 3.0.5 on 2020-04-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20200413_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='houses.Category'),
        ),
        migrations.AddField(
            model_name='house',
            name='dstv',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='houses.Dstv'),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='house',
            name='wifi',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='houses.Wifi'),
        ),
    ]
