# Generated by Django 3.0.5 on 2020-04-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='houses.Room'),
        ),
    ]
