# Generated by Django 3.0.5 on 2020-04-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_house_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Category'),
        ),
        migrations.AlterField(
            model_name='house',
            name='dstv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Dstv'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Room'),
        ),
        migrations.AlterField(
            model_name='house',
            name='wifi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Wifi'),
        ),
    ]
