# Generated by Django 3.0.5 on 2020-04-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20200413_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dstv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Dstv',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Wifi',
        ),
    ]
